INSERT INTO fees_structure (expenses, TERM_1, TERM_2, TERM_3, classes, course, activated, roles) VALUES 
('CLINICAL OFFICERS COUNCIL FEE', '7500','0','0','Diploma','1','1','provisional'),
('CLINICAL OFFICERS COUNCIL FEE', '7500','0','0','Diploma','2','1','provisional'),
('Registration fee', '1000','0','0','Diploma','1','1','provisional'),
('Registration fee', '1000','0','0','Diploma','2','1','provisional'),
('Log Book', '1000','0','0','Diploma','1','1','provisional'),
('Log Book', '1000','0','0','Diploma','2','1','provisional'),
('Graduation Fee', '5500','0','0','Diploma','1','1','provisional'),
('Graduation Fee', '5500','0','0','Diploma','2','1','provisional'),
('Industrial Attachment Fee', '4000','0','0','Diploma','1','1','provisional'),
('Industrial Attachment Fee', '4000','0','0','Diploma','2','1','provisional'),
('HEPATITIS B. VACCINE', '3000','0','0','Diploma','1','1','provisional'),
('HEPATITIS B. VACCINE', '3000','0','0','Diploma','2','1','provisional'),
('Uniform ', '6000','0','0','Diploma','1','1','provisional'),
('Uniform ', '6000','0','0','Diploma','2','1','provisional'),
('Library Fee', '1500','0','0','Diploma','1','1','regular'),
('Library Fee', '1500','0','0','Diploma','2','1','regular'),
('Students` representative council (SRC)-Fee', '500','0','0','Diploma','1','1','regular'),
('Students` representative council (SRC)-Fee', '500','0','0','Diploma','2','1','regular'),
('Examination fee', '2000','0','0','Diploma','1','1','regular'),
('Examination fee', '2000','0','0','Diploma','2','1','regular'),
('Activity fee', '1000','0','0','Diploma','1','1','provisional'),
('Activity fee', '1000','0','0','Diploma','2','1','provisional'),
('ICT Services', '1500','0','0','Diploma','1','1','regular'),
('ICT Services', '1500','0','0','Diploma','2','1','regular'),
('Student ID', '500','0','0','Diploma','1','1','provisional'),
('Student ID', '500','0','0','Diploma','2','1','provisional'),
('LUNCH ONLY', '10000','0','0','Diploma','1','1','regular'),
('LUNCH ONLY', '10000','0','0','Diploma','2','1','regular');

INSERT INTO fees_structure (expenses, TERM_1, TERM_2, TERM_3, classes, course, activated, roles) VALUES
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','3','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','4','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','5','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','6','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','7','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','8','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','9','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','10','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','11','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','12','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','13','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','14','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','15','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','16','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','17','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','19','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma (Internal Certification)','20','1','provisional');

INSERT INTO fees_structure (expenses, TERM_1, TERM_2, TERM_3, classes, course, activated, roles) VALUES
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','57','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','58','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','59','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','60','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','61','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','62','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','63','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','64','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','65','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','66','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','67','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','68','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','69','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','70','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','71','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','72','1','provisional'),
('Student Activity Fee (Trips, Industry Experts) (Annual)', '1000','0','0','Diploma(KNEC/TVET CDACC Certification)','73','1','provisional');
